require(['core/first','theme_bootstrapbase/pending'],function(){require(['theme_bootstrapbase/bootstrap','core/log'],function(bootstrap,log){log.debug('Bootstrap initialised')})});
function customise_dock_for_theme(dock){dock.on('dock:panelgenerated',function(){dock.get('panel').once('dockpanel:beforeshow',function(){Y.all('.dockeditempanel_content').addClass('block')});dock.get('panel').on('dockpanel:beforeshow',function(){var content=Y.all('.dockeditempanel_content');content.setStyle('maxWidth',content.get('winWidth')-dock.get('dockNode').get('offsetWidth')-10)})});dock.on('dock:initialised',function(){var navbar=Y.one('header.navbar'),navbarbtn=Y.one('header.navbar .btn-navbar'),navcollapse=Y.one('header.navbar .nav-collapse'),container=Y.one('#dock .dockeditem_container'),margintop=null,newmargintop=null,diff=null;if(navbar&&navbarbtn&&container){margintop=parseInt(container.getStyle('marginTop').replace(/px$/,''),10);diff=margintop-parseInt(navbar.get('offsetHeight'),10);navbarbtn.ancestor().on('click',function(){navcollapse.toggleClass('active');if(!this.hasClass('active')){newmargintop=(parseInt(navbar.get('offsetHeight'),10)+diff);container.setStyle('marginTop',newmargintop+'px')}else{container.setStyle('marginTop',margintop+'px')}
navcollapse.toggleClass('active');dock.fire('dock:itemschanged')},navbarbtn)}})};
$(document).ready(function(){if($("#navigation-wrapper .main-navigation-inner .nav")){$("#navigation-wrapper .main-navigation-inner .nav").addClass("main-menu theme-ddmenu");$("#navigation-wrapper .main-navigation-inner .nav").removeClass("nav")}
if($("#navigation-wrapper .main-navigation-inner .main-menu")){$("#navigation-wrapper .main-navigation-inner .main-menu").attr({"data-animtype":2,"data-animspeed":450});$("#navigation-wrapper .main-navigation-inner .main-menu li.dropdown ul.dropdown-menu").removeClass("dropdown-menu").addClass("dropdown-list");$("#navigation-wrapper .main-navigation-inner .main-menu li.dropdown a.dropdown-toggle b.caret").removeClass("caret").addClass("mobile-arrow")}
if($("#navigation-wrapper .main-navigation-inner .main-menu li.dropdown ul.dropdown-list li.dropdown-submenu")){$("#navigation-wrapper .main-navigation-inner .main-menu li.dropdown ul.dropdown-list li.dropdown-submenu").removeClass("dropdown-submenu").addClass("dropdown")}
$('.owl-carousel').owlCarousel({loop:!0,margin:25,nav:!1,autoplay:5000,responsiveClass:!0,responsive:{0:{items:1,nav:!0},600:{items:3,nav:!1},1000:{items:4,nav:!0,loop:!1,}}});$(window).scroll(function(){if($(this).scrollTop()>10){$('#backtotop ').fadeIn()}else{$('#backtotop').fadeOut()}});$('#backtotop a').click(function(){$("html, body").animate({scrollTop:0});return!1});if($('.frontpage-course-list-all')){$('.frontpage-course-list-all').parent('div').addClass("ourcourses")}
$("div.ourcourses > h2").addClass("all");var elements=document.getElementsByClassName('all');for(var i=0;i<elements.length;i++){if(elements[i].innerHTML=='Available courses'){elements[i].innerHTML="Our Courses";break}}
$("div.ourcourses h2.all").after("<p class='tagline'>You can see all our courses here.</p>");if($('#frontpage-course-list')){$('#frontpage-course-list .coursebox').addClass('span3')}
$('body #frontpage-course-list').each(function(){$(this).addClass('clearfix')});var ourCourses=$('.ourcourses').html();if(typeof ourCourses!=='undefined'&&ourCourses!==null){$('#course-collection > .container-fluid').append('<div id="frontpage-course-list" class="ourcourses clearfix">'+ourCourses+'</div>');$('#region-main .ourcourses').css({'display':'none'})};if($('.ourcourses').length===0){$('#page #course-collection').css({'display':'none'})}
try{var mainWrapper=$('.frontpage-course-list-all, .frontpage-course-list-enrolled');if(mainWrapper){mainWrapper.each(function(index,obj){var coursebox=$(obj).find('.coursebox');if(coursebox){coursebox.each(function(index,obj){var courseimage=$(obj).find('.content .courseimage');var findDiv=$(obj).find('.info');if(courseimage.length>0){courseimage.insertBefore(findDiv)}})}})}}catch(ignore){}
try{var _frontpageCourseListAll=$('.frontpage-course-list-all');var frontpageCourseListAll=$(_frontpageCourseListAll[0]);if(frontpageCourseListAll){var totalPageWidth=$(frontpageCourseListAll).width();frontpageCourseListAll.find('.coursebox').addClass('proxyW');var courseBoxWidth=frontpageCourseListAll.find('.coursebox:first').outerWidth(!0);var allBoxes=frontpageCourseListAll.find('.coursebox');var totalBoxes=allBoxes.length;var boxesPerRow=Math.floor(totalPageWidth/courseBoxWidth);frontpageCourseListAll.find('.coursebox').removeClass('proxyW');var temp2,temp3,shadowPAGE=$('<div class="shadow-frontpage-course-list-all row-fluid"></div>');for(temp2=0;temp2<boxesPerRow;temp2++){shadowPAGE.append('<div class="course-section span3  course-section-'+temp2+'"></div>')}
for(temp2=0,temp3=0;temp2<totalBoxes;temp2++,temp3=(temp3<(boxesPerRow-1)?temp3+1:0)){shadowPAGE.find('.course-section-'+temp3).append($(allBoxes[temp2]).clone())}
var pageingMore$=$('.frontpage-course-list-all .paging-morelink');if(pageingMore$!=null&&pageingMore$.length>0){shadowPAGE.append(pageingMore$)}
shadowPAGE.append('<div class="clearfix"></div>');frontpageCourseListAll.html(shadowPAGE)}}catch(ignore){}
try{var _frontpageCourseListAllS=$('.frontpage-course-list-all');var frontpageCourseListAllS=$(_frontpageCourseListAllS[1]);if(frontpageCourseListAllS){var _totalPageWidth=$(frontpageCourseListAllS).width();var _courseBoxWidth=frontpageCourseListAllS.find('.coursebox:first').outerWidth(!0);var _allBoxes=frontpageCourseListAllS.find('.coursebox');var _totalBoxes=_allBoxes.length;var _boxesPerRow=Math.floor(_totalPageWidth/_courseBoxWidth);var temp2,_temp3,_shadowPAGE=$('<div class="shadow-frontpage-course-list-all row-fluid"></div>');for(_temp2=0;_temp2<_boxesPerRow;_temp2++){_shadowPAGE.append('<div class="course-section span3 course-section-'+_temp2+'"></div>')}
for(_temp2=0,_temp3=0;_temp2<_totalBoxes;_temp2++,_temp3=(_temp3<(_boxesPerRow-1)?_temp3+1:0)){_shadowPAGE.find('.course-section-'+_temp3).append($(_allBoxes[_temp2]).clone())}
var pageingMore$=$('.frontpage-course-list-all .paging-morelink');if(pageingMore$!=null&&pageingMore$.length>0){_shadowPAGE.append(pageingMore$)}
_shadowPAGE.append('<div class="clearfix"></div>');frontpageCourseListAllS.html(_shadowPAGE)}}catch(ignore){}
if($('.frontpage-course-list-all')){$('.frontpage-course-list-all .coursebox').removeClass('span3')}
$('.frontpage-course-list-enrolled').parent('div').addClass("mycourses");$("div.mycourses > h2").addClass("my");$("div.mycourses h2.my").after("<p class='tagline'>Here You Can See All Your Enrolled Courses.</p>");try{var frontpageCourseListEnrolled=$('.frontpage-course-list-enrolled');var totalPageWidth=$(frontpageCourseListEnrolled).width();var courseBoxWidth=frontpageCourseListEnrolled.find('.coursebox:first').outerWidth(!0);var enrolledBoxes=frontpageCourseListEnrolled.find('.coursebox');var totalBoxes=enrolledBoxes.length;var boxesPerRow=Math.floor(totalPageWidth/courseBoxWidth);var temp2,temp3,shadowPAGE=$('<div class="shadow-frontpage-course-list-enrolled row-fluid"></div>');for(temp2=0;temp2<boxesPerRow;temp2++){shadowPAGE.append('<div class="course-section span3 course-section-'+temp2+'"></div>')}
for(temp2=0,temp3=0;temp2<totalBoxes;temp2++,temp3=(temp3<(boxesPerRow-1)?temp3+1:0)){shadowPAGE.find('.course-section-'+temp3).append($(enrolledBoxes[temp2]).clone())}
var pageingMore$=$('.frontpage-course-list-enrolled .paging-morelink');if(pageingMore$!=null&&pageingMore$.length>0){shadowPAGE.append(pageingMore$)}
shadowPAGE.append('<div class="clearfix"></div>');frontpageCourseListEnrolled.html(shadowPAGE)}catch(ignore){}
if($('.frontpage-course-list-enrolled')){$('.frontpage-course-list-enrolled .coursebox').removeClass('span3')}
var myCourses=$('.mycourses').html();if(typeof myCourses!=='undefined'&&myCourses!==null){$('#mycourse-collection > .container-fluid').append('<div id="frontpage-course-list" class="mycourses clearfix">'+myCourses+'</div>');$('#region-main .mycourses').css({'display':'none'})};if($('.mycourses').length===0){$('#page #mycourse-collection').css({'display':'none'})}
var SiteNewsForum=$('#site-news-forum').html();if(typeof SiteNewsForum!=='undefined'&&SiteNewsForum!==null){if($('#latest-news > .span6')){$('#latest-news > .span6').prepend('<div id="site-news-forum">'+SiteNewsForum+'</div>')}
if($('#region-main #site-news-forum')){$('#region-main #site-news-forum').remove()}
if($('#region-main #site-news-forum > .forum')){$('#region-main #site-news-forum > .forum').remove()}};if($('#site-news-forum').length===0){$('#page #latest-news').css({'display':'none'})}
if($("#site-news-forum .forumpost")){$("#site-news-forum .forumpost").addClass("item")}
if($("#site-news-forum .forumpost")){$("#site-news-forum .forumpost").wrapAll("<div id='owl-demo1' class='owl-carousel owl-theme'></div>")}
if($('body').hasClass('dir-rtl')===!0){$('#owl-demo1').addClass('owl-rtl');$("#owl-demo1").owlCarousel({rtl:!0,loop:!1,margin:10,responsiveClass:!0,responsive:{0:{items:1,},600:{items:1,},1000:{items:1,loop:!1}}})}else{$("#owl-demo1").owlCarousel({rtl:!1,loop:!1,margin:10,responsiveClass:!0,responsive:{0:{items:1,},600:{items:1,},1000:{items:1,loop:!1}}})}
var showChar=50;var ellipsestext=" ";var moretext="more...";var lesstext="...less";$('.coursebox .content').each(function(index,obj){var tHTML="";var teachers=$(obj).find('.teachers');if(teachers.length>0){var tHTML=teachers.html()}
if($(this).children('.teachers')){$(this).children('.teachers').remove()}
var content=$(this).html();if(content.length>showChar){content=strip(content);function strip(html){var tmp=document.createElement("DIV");tmp.innerHTML=html;return tmp.textContent||tmp.innerText}
var c=content.substr(0,showChar);var h=content.substr(showChar,content.length-showChar);var html=c+'<span class="moreellipses">'+ellipsestext+' </span><span class="morecontent"><span>'+h+"<ul class='teachers'>"+tHTML+"</ul>"+'</span>  <a href="" class="morelink">'+moretext+'</a></span>';$(this).html(html);var teachersNode=$(this).children('.morecontent').children('span').children('.teachers');if(teachersNode){var tInnerHTML=teachersNode.html();if(tInnerHTML===""){teachersNode.remove()}}}});$(".morelink").click(function(){if($(this).hasClass("less")){$(this).removeClass("less");$(this).html(moretext)}else{$(this).addClass("less");$(this).html(lesstext)}
$(this).parent().prev().toggle();$(this).prev().toggle();return!1});$('.frontpage-category-combo').addClass("clearfix");var ComboCoursesH2=$('#frontpage-category-combo > h2').html();if(typeof ComboCoursesH2!=='undefined'&&ComboCoursesH2!==null){$('li.combo > a').prepend('<h2>'+ComboCoursesH2+'</h2>');$('#region-main #frontpage-category-combo > h2').css({'display':'none'})};var ComboCoursesTree=$('#frontpage-category-combo > .course_category_tree').html();if(typeof ComboCoursesTree!=='undefined'&&ComboCoursesTree!==null){$('div#combocourses').prepend('<div class="course_category_tree">'+ComboCoursesTree+'</div>');$('#region-main #frontpage-category-combo > .course_category_tree').css({'display':'none'})};$('.frontpage-category-names').addClass("clearfix");var listCoursesH2=$('#frontpage-category-names > h2').html();if(typeof listCoursesH2!=='undefined'&&listCoursesH2!==null){$('li.category > a').prepend('<h2>'+listCoursesH2+'</h2>');$('#region-main #frontpage-category-names > h2').css({'display':'none'})};var CategoryCoursesTree=$('#frontpage-category-names > .frontpage-category-names').html();if(typeof CategoryCoursesTree!=='undefined'&&CategoryCoursesTree!==null){$('div#categorylist').prepend('<div class="frontpage-category-names course_category_tree">'+CategoryCoursesTree+'</div>');$('#region-main #frontpage-category-names > .frontpage-category-names').css({'display':'none'})};$('ul.custom-nav-tabs li > a > h2').addClass('activeh2');$('h2.activeh2:first').parent().parent().addClass('active');$('div.tabs-holder > div.tab-content > div > div').addClass('activediv');$('div.activediv:first').parent().addClass('active');$('ul.tabrow0').addClass('nav-tabs');try{var container_fluid=$('.container-fluid');if(container_fluid){var navigation=container_fluid.find('.tabs-holder ul.nav');if(navigation){var category=navigation.find('li.category a h2');var combo=navigation.find('li.combo a h2');if(category.length===0&&combo.length===0){navigation?navigation.parents('.tabs-holder').addClass('hidden'):''}}}}catch(ignore){}
var langmenu=$('.langmenu').html();if(typeof langmenu!=='undefined'&&langmenu!==null){$('ul.short-menu').append('<li class="dropdown langmenu">'+langmenu+'</li>');$('ul.theme-ddmenu li.langmenu').css({'display':'none'})};if($('.langmenu').length===0){$('ul.theme-ddmenu').css({'display':'none'})}
if($('.paging-morelink > a')){$('.paging-morelink > a').addClass('paging-morelink-link')}
var elements=document.getElementsByClassName('paging-morelink-link');if(elements){for(var i=0;i<elements.length;i++){if(elements[i].innerHTML=='All courses'){elements[i].innerHTML="View all courses";break}}}
if($(".paging-morelink-link")){$(".paging-morelink-link").append(" <i class='fa fa-long-arrow-right' aria-hidden='true'></i>")}
if($("#page-login-index")){if($(".signuppanel .subcontent").length===0){$(".signuppanel").addClass('hidden')}else{$(".signuppanel.hidden").removeClass('hidden')}}});
$(function(){$('.theme-ddmenu').each(function(){var menuList=$(this),animType=menuList.data('animtype'),animSpeed=menuList.data('animspeed'),mobileArr=menuList.find('.mobile-arrow');menuList.superfish({popUpSelector:'ul',hoverClass:'mb2ctm-hover',animation:animType==2?{height:'show'}:{opacity:'show'},speed:animSpeed,speedOut:'fast',cssArrows:!1});menuOnHover(menuList);$(window).on('resize',function(){menuOnHover(menuList)});mobileArr.click(function(e){e.preventDefault();$(this).parent().siblings('ul').slideToggle(250);$(this).toggleClass('active')})
function menuOnHover(list){var w=(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth);if(w<=768){list.removeClass('sf-js-enabled');list.removeClass('desk-menu');list.addClass('mobile-menu')}else{list.addClass('sf-js-enabled');list.removeClass('mobile-menu');list.addClass('desk-menu');list.find('.mobile-arrow').removeClass('active');list.find('.mobile-arrow').parent().siblings('ul').hide()}}})
function customAccordion(header,content){header.click(function(e){e.preventDefault();$(this).toggleClass('active');content.slideToggle(250)})};$(document).on('click','.show-menu',function(e){e.preventDefault();var menuList=$(this).parent().parent().find('.theme-ddmenu');menuList.slideToggle(250)});setTimeout(function(){makeFixedNavigation()},10);$(window).scroll(function(){makeFixedNavigation()})
function makeFixedNavigation(){var win=$(window),offsetEl=$('.fixed-nav-element');if(offsetEl.length!=0&&$('body').hasClass('fixed-nav')){var fixedEl=$('#nav-main'),fixedElWrap=fixedEl.parent(),elOffset=offsetEl.offset().top,fixElHeight=fixedEl.outerHeight(!0);if(win.scrollTop()>elOffset){fixedEl.addClass('navbar-fixed-top');offsetEl.css({height:fixElHeight})}else{fixedEl.removeClass('navbar-fixed-top');offsetEl.css({height:0})}}}})